### ISSUE TITLE
Broken equation crossref

### ISSUE THREAD

**Issue by Aariq** [quarto-ext/manuscript-template-jupyter#1]
I hope I'm in the right place here.  I assume this is the source code for https://quarto-ext.github.io/manuscript-template-jupyter/.  I noticed a broken equation cross reference in the live demo:

![Screenshot 2024-01-30 at 3 07 11 PM](https://github.com/quarto-ext/manuscript-template-jupyter/assets/25404783/40c7c14e-f9ef-4748-a451-937764f28539)

My guess is probably a missing linebreak or something

**Comment by cderv** [comment]
@dragonstyle I don't see the issue in the syntax. VSCODE and RSTUDIO version of template seems to work. 
But for this one, I get error while rendering
```
WARNING (C:/Users/chris/Documents/DEV_R/quarto-cli/src/resources/filters/./crossref/refs.lua:136) Unable to resolve crossref @eq-poisson
```

so something does not seem to work. Could we have an issue ? 

Also I am not sure if I am correctly setup. Github action is not working either here - so I don't who is in charge for now to render new version. Can you check ? 

cc @cwickham as it could also be you. 

Happy to help setup CI if needed.

**Comment by dragonstyle** [comment]
Thanks for catching this- I updated the and re-rendered. I noticed that the line endings in the notebook file were `\r` which was odd (and I can't explain).

**Comment by dragonstyle** [comment]
(The GH action does appear to be working for me - it only is set to trigger on commits to main right now)

**Comment by cderv** [comment]
> (The GH action does appear to be working for me - it only is set to trigger on commits to main right now)

Oh right - ok then. I saw ipynb and no `_freeze` and thought python was required which the action does not setup, but I guess we don't need to execute again. So all good. 

Seems fixed now ! thanks !
